chore(deps): bump activesupport from 7.2.3.2 to 7.2.4 in /libraries/react-native-iap/example (#496)
Bumps [activesupport](https://github.com/rails/rails) from 7.2.3.2 to
7.2.4.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/releases">activesupport's
releases</a>.</em></p>
<blockquote>
<h2>7.2.4</h2>
<h2>Active Support</h2>
<ul>
<li>
<p>Improve <code>number_to_delimited</code> performance when
<code>delimiter_pattern</code> is not specified.</p>
<p><em>Shinichi Maeshima</em></p>
</li>
<li>
<p>Silence Dalli 4.0+ warning when using
<code>ActiveSupport::Cache::MemCacheStore</code>.</p>
<p><em>zzak</em></p>
</li>
<li>
<p>Fix <code>ActiveSupport::Inflector.humanize</code> with international
characters.</p>
<pre
lang="ruby"><code>ActiveSupport::Inflector.humanize(&quot;áÉÍÓÚ&quot;) #
=&gt; &quot;Áéíóú&quot;
ActiveSupport::Inflector.humanize(&quot;аБВГДЕ&quot;) # =&gt;
&quot;Абвгде&quot;
</code></pre>
<p><em>Jose Luis Duran</em></p>
</li>
</ul>
<h2>Active Model</h2>
<ul>
<li>No changes.</li>
</ul>
<h2>Active Record</h2>
<ul>
<li>
<p>Fix performance regression in <code>method_missing</code> for virtual
SELECT alias
attributes.</p>
<p>Fixes <a
href="https://redirect.github.com/rails/rails/issues/57183">#57183</a>.</p>
<p><em>Hammad Khan</em></p>
</li>
<li>
<p>Fix support for table names containing hyphens.</p>
<p><em>Evgeniy Demin</em></p>
</li>
<li>
<p>Improve PostgreSQLAdapter resilience to Timeout.timeout.</p>
<p>Better handle asynchronous exceptions being thrown inside
the <code>reconnect!</code> method.</p>
<p>This may fixes some deep errors such as:</p>
<pre><code>undefined method `key?' for nil:NilClass (NoMethodError)
          if !type_map.key?(oid)
</code></pre>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/rails/rails/commit/48e05e6355f9c617758df1ee4f8c3f555d0f3d74"><code>48e05e6</code></a>
Preparing for 7.2.4 release</li>
<li><a
href="https://github.com/rails/rails/commit/da8a14b7ff2c98702e8afb896cdd66fd9b419f77"><code>da8a14b</code></a>
Sync CHANGELOG</li>
<li><a
href="https://github.com/rails/rails/commit/59c76d2610cc0c086678f7ef0b0a475aca80e73e"><code>59c76d2</code></a>
Stop passing <code>quirks_mode</code> to JSON.parse</li>
<li><a
href="https://github.com/rails/rails/commit/7b7a54c7c3777670f6c64c7031c6e3a8947763a0"><code>7b7a54c</code></a>
Merge branch '7-2-sec' into 7-2-stable</li>
<li><a
href="https://github.com/rails/rails/commit/ba85d431e2027bd0b0ebc598ceec95232e9be4bd"><code>ba85d43</code></a>
Revert &quot;Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/57832">#57832</a>
from yahonda/bump-json-2-20-0&quot;</li>
<li><a
href="https://github.com/rails/rails/commit/83fb66da4087206612f0ab8bf6057718c199f471"><code>83fb66d</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/57832">#57832</a>
from yahonda/bump-json-2-20-0</li>
<li><a
href="https://github.com/rails/rails/commit/90081753b1489672a4bfe3a1defbeed561b8a8dc"><code>9008175</code></a>
Don't defer output when not running in CI</li>
<li><a
href="https://github.com/rails/rails/commit/11f972a5dd3550375ff32f756e54b7a8d5bc1d47"><code>11f972a</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/57069">#57069</a>
from willnet/remove-default-delimite-regex</li>
<li><a
href="https://github.com/rails/rails/commit/45d0a26e79ddf15d2f36b228a0cab939fe26900a"><code>45d0a26</code></a>
Merge branch '7-2-sec' into 7-2-stable</li>
<li><a
href="https://github.com/rails/rails/commit/2ccdd4892d46f884705c19548cb61ca0f0c9aefa"><code>2ccdd48</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/56652">#56652</a>
from zzak/re-56588</li>
<li>Additional commits viewable in <a
href="https://github.com/rails/rails/compare/v7.2.3.2...v7.2.4">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=activesupport&package-manager=bundler&previous-version=7.2.3.2&new-version=7.2.4)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>